[package]
name = "emu-invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu-8080 = { path = "../emu-8080" }
minifb = "0.19.2"
rodio = "0.20.1"

[features]
logging = ["emu-8080/logging"]